#!/usr/bin/env bash

. ~/.git-scripts/git-ref >/dev/null \
    && . ~/.git-scripts/git-branches >/dev/null \
    || exit

git fetch --all

for branch in $branches; do
    git checkout "$branch"

    git rev-parse "@{push}" &>/dev/null || continue

    if ! git are-no-conflicts "$branch" "@{push}"; then
        echo "branch '$branch' has merge conflicts" >&2
        continue
    fi

    git rebase "@{push}"
done

git checkout --quiet "$ref"
